# Generated by Django 3.2.2 on 2021-05-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_compiler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compiler',
            old_name='name',
            new_name='Author',
        ),
    ]
