# Generated by Django 3.2.2 on 2021-05-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_compiler', '0002_rename_name_compiler_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codedata', models.TextField()),
                ('outputarea', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='compiler',
        ),
    ]
